language: java
jdk:
  - oraclejdk7
  - oraclejdk8
services:
  - mongodb
install:
  - sh -c 'cd querydsl-root && mvn -B -q install -Dmaven.javadoc.skip=true -DskipTests=true'
script:
  - sh -c 'cd querydsl-root && mvn -B test'
