language: java
jdk:
  - oraclejdk8
services:
  - docker
env:
  matrix:
    - MODULE=!querydsl-scala PROFILES=all,travis,examples
    - MODULE=!querydsl-jpa-codegen PROFILES=jpa,hibernate5,travis,examples
    - MODULE=querydsl-scala PROFILES=all,travis
install: /bin/true
before_script:
  - sudo /etc/init.d/mysql stop
  - ./travis/docker_bootstrap.sh
script: mvn --batch-mode test --activate-profiles ${PROFILES} --projects ${MODULE} jacoco:report
sudo: required
after_success:
  - mvn coveralls:report
cache:
  directories:
    - $HOME/.m2
