dist: xenial
language: java
jdk:
  - openjdk8
services:
  - docker
env:
  matrix:
    - ARGS='--activate-profiles all,travis,examples --projects !querydsl-scala'
    - ARGS='--activate-profiles jpa,hibernate5,travis,examples --projects !querydsl-jpa-codegen'
    - ARGS='--activate-profiles all,travis --projects querydsl-scala --resume-from querydsl-scala'

install: mvn clean install -DskipTests
before_script:
  - docker-compose --file travis/docker-compose.yml up --detach mysql postgresql mongo

script:
  - mvn --batch-mode verify -am jacoco:report ${ARGS}
after_success:
  - mvn coveralls:report

before_cache:
  - rm -rf $HOME/.m2/repository/com/querydsl/
cache:
  directories:
    - $HOME/.m2
