language: java
jdk:
  - oraclejdk7
services:
  - mongodb
addons:
  postgresql: "9.3"
install:
  - sh -c 'cd querydsl-root && mvn -B -q install -Dmaven.javadoc.skip=true -DskipTests=true'
before_script:
  - mysql -e "create database querydsl;" -u root
  - mysql -e "create database querydsl2;" -u root
  - mysql -e "create user 'querydsl'@'localhost' identified by 'querydsl';" -u root
  - mysql -e "grant all privileges on querydsl.* to 'querydsl'@'localhost';" -u root
  - mysql -e "grant all privileges on querydsl2.* to 'querydsl'@'localhost';" -u root
  - psql -c 'create database querydsl;' -U postgres
  - psql -c 'create database querydsl2;' -U postgres
  - psql -c "create user querydsl with password 'querydsl';" -U postgres
  - psql -c 'grant all privileges on database querydsl to querydsl;' -U postgres
  - psql -c 'grant all privileges on database querydsl2 to querydsl;' -U postgres
  - psql -c 'create extension postgis;' -d querydsl -U postgres
  - echo 'yes' | sudo add-apt-repository ppa:cubrid/cubrid
  - sudo apt-get update
  - sudo apt-get install cubrid
  - sudo apt-get install cubrid-demodb
  - /etc/profile.d/cubrid.sh
  - hostname | sed 's/^/127.0.0.1 /g' | cat - /etc/hosts > /tmp/etchoststemp && sudo mv /tmp/etchoststemp /etc/hosts --force
  - sudo apt-get install firebird2.5-superclassic
  - sudo isql-fb -r sysdba -pas masterkey -input firebird.sql
script:
  - sh -c 'cd querydsl-root && mvn -B test -Pall,travis'
